config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'welcome#index'
  resources :articles

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registrable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(path)
    "active" if current_page? path
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  = if @article.errors.any?
    #error_explanation
    %h2
      = pluralize(@article.errors.count, "error")
      prohibited this article from being saved:
    %ul
      - @article.errors.full_messages.each do |msg|
        %li= msg
  = f.label :title
  = f.text_field :title

  = f.label :text
  = f.text_area :text

  = f.submit "Save"

app/views/articles/edit.html.haml
%h1 Edit Article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 All Articles
- if admin_signed_in?
  = link_to 'New article', new_article_path

- @articles.each do |article|
  %h3= article.title
  %p= article.text
  = link_to 'Show', article_path(article)
  - if admin_signed_in?
    = link_to 'Edit', edit_article_path(article)
    = link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }

app/views/articles/new.html.haml
%h1 New Article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%h1= @article.title
%p= @article.text

= link_to 'Back', articles_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %link{href: "http://fonts.googleapis.com/css?family=Roboto:400,100,300,700", rel: "stylesheet", type: "text/css"}
    %title= content_for?(:title) ? yield(:title) : "Vicente Yarad"
    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .hero
      - if notice
        %p.notice= notice
      - if alert
        %p.alert= alert
      %nav
        .row
          .small-12.columns.clearfix
            = link_to "VY", root_path, class: "left logo"
            %ul.inline-list.right
              %li
                = link_to "Me", root_path, class: is_active?(root_path)
              %li
                = link_to "Portafolio", articles_path, class: is_active?(articles_path)
              %li
                = link_to "Contact", "mailto:hey@vicenteyarad.com"
              %li
                - if admin_signed_in?
                  = link_to "Logout", destroy_admin_session_path, method: :delete
                - else
                  = link_to "Sign-in", new_admin_session_path, class: is_active?(new_admin_session_path)
    = yield

app/views/welcome/index.html.haml
.me
.row
  .small-12.columns
    %h1.welcome-title.text-center Vicente Yarad
    %p.text-center Web Designer
    = link_to "Portafolio", articles_path, class: "main-button button radius"

.row
  .small-12.columns
    %ul.social.inline-list.text-center
      %li
        = link_to "" do
          = fa_icon "facebook"
      %li
        = link_to "" do
          = fa_icon "twitter"
      %li
        = link_to "" do
          = fa_icon "github"
      %li
        = link_to "" do
          = fa_icon "envelope-o"